version: "3"

services:
  app:
    build:
      context: go
    container_name: go
    tty: true 
    entrypoint: go run /src/cmd/server/server.go
    volumes:
      - ./go:/src
    ports:
      - "8080:8080"